import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jingxu-private-voice-'));
process.env.DW_TEST_DATA_DIR=dir;process.env.DW_SKIP_STARTUP_RECOVERY='1';
const {db}=await import('../lib/db.ts');
const {ownedVoice,verifiedPersonalReference,voiceReferenceDirectory,personalVoiceOut}=await import('../lib/personal-voices.ts');
test('personal references enforce account ownership, readiness, archive and content hash',()=>{
 const id=randomUUID();db.prepare('INSERT INTO personal_voices(id,created_by,name,source_ids_json,status,created_at) VALUES(?,?,?,?,?,?)').run(id,'alice','Private voice','["source"]','new',new Date().toISOString());
 assert.equal(ownedVoice(id,'bob'),undefined);
 assert.throws(()=>verifiedPersonalReference(id,'alice'),/尚未准备/);
 assert.throws(()=>voiceReferenceDirectory('../escape'),/无效/);
 const root=voiceReferenceDirectory(id);fs.mkdirSync(root,{recursive:true});
 const bytes=Buffer.from('test reference bytes, not a real audio quality test');
 fs.writeFileSync(path.join(root,'reference.wav'),bytes);
 fs.writeFileSync(path.join(root,'reference-report.json'),JSON.stringify({referenceSha256:createHash('sha256').update(bytes).digest('hex')}));
 db.prepare("UPDATE personal_voices SET status='ready' WHERE id=?").run(id);
 assert.equal(verifiedPersonalReference(id,'alice'),root);
 assert.throws(()=>verifiedPersonalReference(id,'bob'),/尚未准备/);
 assert.deepEqual(Object.keys(personalVoiceOut(ownedVoice(id,'alice'))).sort(),['createdAt','id','name','sourceIds','status']);
 db.prepare('UPDATE personal_voices SET archived=1 WHERE id=?').run(id);
 assert.equal(ownedVoice(id,'alice'),undefined);
 assert.equal(verifiedPersonalReference(id,'alice',true),root,'existing tasks retain archived voice');
 fs.writeFileSync(path.join(root,'reference.wav'),'modified');
 assert.throws(()=>verifiedPersonalReference(id,'alice',true),/校验/);
});
test.after(()=>db.close());
